#!/usr/bin/env python

import os
import sys

ALLENVS = sorted(sys.argv[1:])
INDEX = int(os.environ.get('CIRCLE_NODE_INDEX', '0'))
TOTAL = int(os.environ.get('CIRCLE_NODE_TOTAL', '1'))

buckets = {i: [] for i in range(TOTAL)}
for i, env in enumerate(ALLENVS):
    buckets[i % TOTAL].append(env)

myenvs = ",".join(buckets[INDEX])
sys.stderr.write("Running envs %s from %s on node %s out of %s.\n" % (
    myenvs, ','.join(ALLENVS), INDEX, TOTAL,
))
sys.stdout.write(myenvs + "\n")
